# Generate a snake eating your contributions.

name: github-contribution-grid-snake

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 🔨 generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: 🚗 push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: github-contribution-grid-snake
          build_dir: dist
          commit_message: 🐍 SNAKE IS CRAWLING!!!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
